### ISSUE TITLE
GT-AC5300能用吗

### ISSUE THREAD

**Issue by weizhen199** [JackMerlin/USBAccelerator#1]

**Comment by JackMerlin** [comment]
可以，但是提升效果相较于上代 BCM (47XX) 提升很不明显，这里主要是因为 ASUS GT-AC5300 所使用的 CPU 是 BCM4908，USB 的读写性能已经远超 1Gbps 有线的最高速度，因此继续使用加速器会因为 1Gbps 的瓶颈体现不出提升效果。不过在无线下可能会有些许提升，但是提升幅度也会非常小。
