### ISSUE TITLE
No Space left error

### ISSUE THREAD

**Issue by abigchopstick** [JackMerlin/USBAccelerator#3]
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
/tmp/usbaccelerator.sh: line 737: can't create /jffs/scripts/smb.postconf: No space left on device
chmod: /jffs/scripts/smb.postconf: No such file or directory

admin@RT-AC86U-4540:/jffs# df
Filesystem           1K-blocks      Used Available Use% Mounted on
ubi:rootfs_ubifs         79016     56540     22476  72% /
devtmpfs                220040         0    220040   0% /dev
tmpfs                   220156       756    219400   0% /var
mtd:bootfs                4480      3396      1084  76% /bootfs
mtd:data                  8192       548      7644   7% /data
tmpfs                   220156      3992    216164   2% /tmp
/dev/mtdblock8           49152     23748     25404  48% /jffs
/dev/sda1              7508756   1113232   5991052  16% /tmp/mnt/sda1

but my jffs still has some 20MB left?

**Comment by abigchopstick** [comment]
Device is AC86U, works before on 6300V2 and AC5300

**Comment by JackMerlin** [comment]
Dear @abigchopstick
I've been busy lately, sorry for the late reply.

First, I don't have the RT-AC86U model, so I can only try to help you troubleshoot.

0. Please tell me your firmware type: (Stock firmware or Merlin firmware)
1. Please tell me your firmware version.
2. Try upgrading to the latest version of the firmware, whether Merlin or stock firmware.
3. Try uninstalling this script if you can run it. If you cannot run the script, delete the script by entering the following in SSH:
```Shell
umount -f /www/images/New_ui/usbstatus.png 2>/dev/null
rm -f /jffs/scripts/smb.postconf 2>/dev/null
rm -f /jffs/scripts/usbstatus.png 2>/dev/null
rm -f /jffs/scripts/usbaccelerator.sh 2>/dev/null
nvram set script_usbmount=""; nvram commit
rm -f /jffs/post-mount 2>/dev/null
service restart_nasapps
```
4. And try to reinstall
5. Please tell me what happened next, thank you.

**Comment by JackMerlin** [comment]
Because I haven't received your reply for a long time, I have closed this issue now. If you still have issue, please reopen it!
