### ISSUE TITLE
Error!新版本的脚本运行在网件R6900设备上，会导致R6900断网，软件卡死等奇怪问题

### ISSUE THREAD

**Issue by why5684784** [JackMerlin/USBAccelerator#6]
@JackMerlin  我原先使用的是1.0版本，运行了几年一直很正常，但是今天我更新到了2.02版之后，就会导致读写速度不稳定，会忽高忽低，aria2卡死，v2ray卡是，断网等奇怪的现象，请问我改怎么操作一下？

**Comment by JackMerlin** [comment]
@why5684784 您好，很抱歉造成了不好的体验，v2.0+ 虽未收到类似问题的报告，但我很乐意协助您找到问题原因。

首先请先确认您安装 v2.0 及更高版本前已经卸载了 v1.0 版本，因为这两个版本会存在互相干扰的可能，并且更新并不会卸载旧版。若需要卸载旧版可执行以下操作：
#### 安装 v2.0 及更高版本后输入下方命令卸载 v1.0 旧版：
```shell
sh /jffs/addons/usbaccelerator/usbaccelerator.sh --clear
```

若您在更新后已经卸载了旧版，则有两种方案，一条路比较困难，需要协助排错，另外一条路比较简单，就是回退至旧版。

#### 若您希望协助排错，请提供更多基本信息：
* 您的固件版本
* 您已经安装的软件/插件列表
* USB加速器 的相关错误代码（若有）
* 您在发现出错前所做的具体操作（越详细越好）

另请注意，v2.0+ 已经推出半年多，已经取得了较为稳定的口碑，所以在无法明确问题原因或得到广泛复现前不会有任何修补计划。

#### 另外这是回退至 v1.0 版本的方法，执行以下代码：
卸载 v2.0+
```shell
sh /jffs/addons/usbaccelerator/usbaccelerator.sh --uninstall
```
安装 v1.0
```shell
/usr/sbin/wget -c -T 30 --no-check-certificate "https://raw.githubusercontent.com/JackMerlin/USBAccelerator/v1.0/usbaccelerator.sh" -O "/tmp/usbaccelerator.sh" && chmod 755 /tmp/usbaccelerator.sh && sh /tmp/usbaccelerator.sh
```

希望问题可以尽快解决。

**Comment by why5684784** [comment]
我在网件R6900，话说AC1900P上测试了，都是2.0失效，1.0好使。固件版本都是梅林改版(koolshare版)380.79.1，网件R6900安装的插件有aria2c,科学上网，AC1900P上的插件只有Aria2c，2.0基本没有提速效果，没有错误代码，可以运行提速，但是提速很不稳定，而且提速量很小。
在2.0版本下，R6900从原先200K/s提速到2-4M/s，aria2下载速度<=2M/s,速度不稳定。ac1900P 从原先2M/s提速到2-4M/s，aria2下载速度<=2M/s，提速也是不稳定。
在1.0版本下，R6900从原先200K/s提速到32M/s，aria2下载速度<=5M/s，速度稳定。ac1900P 从原先2M/s提速到32M/s，aria2下载速度<=6M/s，速度稳定。

**Comment by JackMerlin** [comment]
非常感谢您协助的测试。

v2.0+ 确实引入了一些机制减少内存的使用，但是可能带来提速不稳定的可能性，这里有一点希望您能澄清，请问您是否使用过任何虚拟内存功能？因为目前尚不明确是否虚拟内存与 v2.0+ 的内存优化有冲突，但是这是一个可能性。

此外若您方便，希望可以提供 v2.0+ 成功启动后在系统日志中的内容（建议安装 v2.0+ 然后重启，重启后提供日志内容）。

另请知悉，USB 加速器仅能提高从路由器到电脑之间使用 SMB 协议相互复制文件的速度，不能提速路由器内部软件、插件读写 USB 的速度，所以若您从 NAS 下载文件到路由器的硬盘中这是有提升空间的，但是若使用路由器自带的 aria2 下载文件，则不存在提速的可能性，因为内部读写文件并不使用 SMB 协议。

**Comment by why5684784** [comment]
我是直接使用的swap命令行挂载的虚拟内存。虽然说内部软件不是用smb协议，走的是bus总线IO，但是也确实提升了速度。

**Comment by JackMerlin** [comment]
请您尝试禁用虚拟内存并重启后再观察 USB加速器 v2.0+ 是否可以带来您所需要的相应改善。

若还有其他疑问欢迎留言回复，此 Issue 暂且关闭。
